"data" :
    "raw" :
        "rnaseq_expression" : 
            "file" : "/data/datasets/raw/rnaseq_expression/HMCL_ensembl74_Counts.txt"
            "description" : "description place holder"
        "gene_ontology" :
            "file" : "/data/datasets/raw/gene_ontology/ensembl_go_mapping.tab"
            "description" : "description"
